status:
  servername: §r§eSun Proxy§r
  playercount: 0
  maxplayers: 50
  showversion: false
hub:
  address: 0.0.0.0
  port: 19133
port: 19132
tcp:
  enabled: false
  #steal my key i dare u lmao
  key: 6Jmcu9Iwj9WkTCEJ1aCqsXH2M
