jobs:
  build:
    docker:
      -
        image: "circleci/golang:1.13"
    steps:
      -
        discord/notify:
          color: "4383476"
          message: "Started Build!"
      - checkout
      -
        run:
          command: "go get -v -t -d ./...;\n"
          name: "Get Modules"
      -
        run:
          command: |
            go build -o sun_linux;
            env GOOS=windows GOARCH=amd64 go build -o sun_windows.exe;
          name: "Build Binaries"
      -
        run:
          command: "mkdir /tmp/artifacts;\n"
          name: "make Artifact Folder"
      -
        run:
          command: |
            mv sun_linux /tmp/artifacts;
            mv sun_windows.exe /tmp/artifacts;
          name: "Move Binaries"
      -
        discord/status: ~
      -
        store_artifacts:
          path: /tmp/artifacts
    working_directory: /go/src/github.com/jviguy/sun
orbs:
  discord: teka23/discord@0.0.1
version: 2.1
